title: "Poornachandar | Cloud Engineer"
email: poornachandar0144@gmail.com
description: >- 
  Cloud Engineer | AWS Certified | Terraform | DevOps | Linux & Windows | Tableau | VMware
baseurl: ""
url: "https://poornachandar.github.io"
linkedin_username: poornachandar19
github_username: your-github-username
theme: minima
